spring:
  application:
    name: microservice-userbase
  datasource:
    name: study
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 1314
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #druid:
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
      
mybatis:
  mapper-locations:
  - classpath*:mapper/**/*.xml

server:
  port: 8750
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      