spring:
  application:
    name: microservice-movie-feign-hystrix

server:
  port: 8211
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: true #开启hystrix支持(Finchley SR2版本spring-cloud默认feign关闭hystrix !)
    
management.endpoints.web.exposure.include: hystrix.stream #将feign加入到dashboard监控中
      
service:    #其他微服务实例名
  name: 
    user-base-service: microservice-userbase
      