spring:
  application:
    name: microservice-movie-ribbon-hystrix

server:
  port: 8769
  
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
management.endpoints.web.exposure.include: hystrix.stream
  
