spring:
  application:
    name: microservice-gateway
    
  cloud:
    gateway:
      routes:
      - id: user-base
        uri: lb://microservice-userbase  #lb 前缀是load balance的缩写,后面跟着服务名可实现ribbon(feign)的负载均衡
        predicates:
        - Path=/yaya/**  #路由映射路径    结合StripPrefix使用是为了路由多项目时将项目区分开来，如果配置path=/** 后面配置的路由将会无效，因为/**会将所有请求拦截
        filters:
        - StripPrefix=1   #strip除去，剥去 ;strip prefix除去前缀; 数字表示除去浏览器请求url前缀里的级数
        
      - id: movie-feign
        uri: lb://microservice-movie-feign-hystrix
        predicates:
        - Path=/lala/**
        filters:
        - StripPrefix=1  
    
server:
  port: 8882
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
#hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000  #hystrix超时调用fallback方法
